// Pełna lista słów z "rz" i "ż" wraz z zasadami ortograficznymi

// Normalized rules for "rz"
const RZ_RULES = {
  AFTER_CONSONANTS: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w.",
  ALTERNATING_WITH_R: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych.",
  PREFIXES: "RZ piszemy w przedrostkach prze-, przy-.",
  MEMORIZE: "RZ piszemy w wyrazach, których pisownię należy zapamiętać. Jest to wyjątek.",
  NUMERALS: "RZ piszemy w liczebnikach zawierających 'trzy'."
};

// Normalized rules for "ż"
const Z_RULES = {
  ALTERNATING: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych.",
  MEMORIZE: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać. Jest to wyjątek.",
  ADJECTIVE_ENDINGS: "Ż piszemy w zakończeniach przymiotników -eży."
};

const rzWordsList = [
  { word: "rzecz", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rzeka", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R },
  { word: "rzut", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R },
  { word: "przyjaźń", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przestrzeń", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyroda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyszłość", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "brzeg", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzoza", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "chrzan", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "drzewo", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzyb", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "krzyk", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "marzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "marzyć - mara" },
  { word: "orzech", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "porzeczka", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzadko", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzadko - rarytas" },
  { word: "rzeźba", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzeźbić - rzeźbiarz" },
  { word: "rzodkiewka", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "trzy", correctAnswer: "rz", rule: RZ_RULES.NUMERALS },
  { word: "wrzesień", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzos", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzawa", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzeciono", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzód", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzesło", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzyż", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzew", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzyczeć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzywda", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "przebaczenie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przepis", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przegląd", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przejście", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przystanek", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przygoda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyjaciel", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przykład", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "burza", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "burza - burzliwy" },
  { word: "morze", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "morze - morski" },
  { word: "górze", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "górze - góra" },
  { word: "tworzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "tworzyć - twór" },
  { word: "powtórzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "powtórzyć - powtór" },
  { word: "przerwa", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "przerwa - przerwać" },
  { word: "spojrzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "spojrzenie - spozierać" },
];

const zWordsList = [
  { word: "żebro", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeton", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeglować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żmudny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółtko", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "nóż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nóż - noże" },
  { word: "mąż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mąż - mężowie" },
  { word: "straż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "straż - strażnik" },
  { word: "stróż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "stróż - stróże" },
  { word: "drażnić", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drażnić - drażniący" },
  { word: "grożenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "grozić - grożenie" },
  { word: "mrożony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mrozić - mrożony" },
  { word: "poważać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "waga - poważać" },
  { word: "pożar", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pożyczka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "rażący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "razić - rażący" },
  { word: "sążeń", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "świeżo", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS },
  { word: "wiążący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wiązać - wiążący" },
  { word: "żaba", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żal", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żart", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żądać", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żelazo", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żniwa", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żona", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółw", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żurek", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyletka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyto", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywioł", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywność", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "bożonarodzeniowy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "bożonarodzeniowy - Bóg" },
  { word: "drużyna", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drużyna - druh" },
  { word: "dłużej", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dłużej - długi" },
  { word: "duży", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "duży - dużo" },
  { word: "książka", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "książka - księga" },
  { word: "krążek", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "krążek - krąg" },
  { word: "leżeć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "leżeć - lęgać" },
  { word: "łoże", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "łoże - lęgać" },
  { word: "możesz", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "możesz - mogę" },
  { word: "odważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "odważny - waga" },
  { word: "pieniężny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "pieniężny - pieniądz" },
  { word: "potężny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "potężny - potęga" },
  { word: "świeży", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS },
  { word: "jeży", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS }
];

export { rzWordsList, zWordsList };