// Pełna lista słów z "rz" i "ż" wraz z zasadami ortograficznymi

// Normalized rules for "rz"
const RZ_RULES = {
  AFTER_CONSONANTS: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w.",
  ALTERNATING_WITH_R: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych.",
  PREFIXES: "RZ piszemy w przedrostkach prze-, przy-.",
  MEMORIZE: "RZ piszemy w wyrazach, których pisownię należy zapamiętać. Jest to wyjątek.",
  NUMERALS: "RZ piszemy w liczebnikach zawierających 'trzy'."
};

// Normalized rules for "ż"
const Z_RULES = {
  ALTERNATING: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych.",
  MEMORIZE: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać. Jest to wyjątek.",
  ADJECTIVE_ENDINGS: "Ż piszemy w zakończeniach przymiotników -eży."
};

const rzWordsList = [
  { word: "zaprzyjaźnić", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "umorzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "umorzyć - mór" },
  { word: "towarzystwo", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "jarzębina", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS, example: "jarzębina - 'rz' po spółgłosce 'j'" },
  { word: "rzecz", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rzeka", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R },
  { word: "rzut", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R },
  { word: "przyjaźń", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przestrzeń", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyroda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyszłość", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "brzeg", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzoza", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "chrzan", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "drzewo", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzyb", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "krzyk", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "marzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "marzyć - mara" },
  { word: "orzech", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "porzeczka", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzadko", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzadko - rarytas" },
  { word: "rzeźba", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzeźbić - rzeźbiarz" },
  { word: "rzodkiewka", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "trzy", correctAnswer: "rz", rule: RZ_RULES.NUMERALS },
  { word: "wrzesień", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzos", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzawa", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzeciono", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzód", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzesło", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzyż", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzew", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzyczeć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "krzywda", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "przebaczenie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przepis", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przegląd", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przejście", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przystanek", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przygoda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyjaciel", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przykład", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "burza", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "burza - burzliwy" },
  { word: "morze", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "morze - morski", context: "W te wakacje pojadę nad {word}" },
  { word: "górze", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "górze - góra" },
  { word: "tworzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "tworzyć - twór" },
  { word: "powtórzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "powtórzyć - powtór" },
  { word: "przerwa", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "przerwa - przerwać" },
  { word: "spojrzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "spojrzenie - spozierać" },
  { word: "przystań", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przeprawa", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przymierze", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyjaźnić", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyjąć", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przejęcie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przeszkoda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przełożyć", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przegroda", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przenikać", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przemysł", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przemyśleć", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przemiana", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przemierzać", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przeróbka", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przeżycie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przesłanie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przestrzegać", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przepływ", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przywódca", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przywilej", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przysięga", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przymiotnik", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przytomność", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przyzwyczajenie", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "przeznaczyć", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "rzecznik", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rzeczywistość", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rzeźnik", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzeźnik - rzeź" },
  { word: "rzęsa", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzucać", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzucać - rzut" },
  { word: "rzemiosło", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzetelny", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzekomy", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzekomy - rzeka" },
  { word: "rządzić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rządzić - rząd" },
  { word: "rzepak", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzepa", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzewny", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzucić - rzut" },
  { word: "brzuch", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzydki", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzęczeć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzask", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzytwa", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzoskwinia", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzeżek", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzemienny", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzuszny", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "brzęk", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzech", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzechotka", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzejnik", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzanka", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzebień", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzęda", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzać", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzeczność", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzesznik", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzebać", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzmot", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grządka", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "marzec", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "marzyciel", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "marzyciel - marzyć" },
  { word: "marznąć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "marznąć - mróz" },
  { word: "mierzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "mierzyć - miara" },
  { word: "wierzba", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wierzch", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wierzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wierzyć - wiara" },
  { word: "wierzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wierzenie - wiara" },
  { word: "wierzenica", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "pomarzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "pomarzenie - marzyć" },
  { word: "orzeźwienie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "orzeźwienie - rześki" },
  { word: "orzeźwiać", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "orzeźwiać - rześki" },
  { word: "stworzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "stworzyć - twór" },
  { word: "wytworzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wytworzyć - twór" },
  { word: "tworzywo", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "tworzywo - twór" },
  { word: "uwierzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "uwierzyć - wiara" },
  { word: "uderzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "uderzyć - uderzenie" },
  { word: "uderzenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "uderzenie - uderzyć" },
  { word: "trzysta", correctAnswer: "rz", rule: RZ_RULES.NUMERALS },
  { word: "trzynaście", correctAnswer: "rz", rule: RZ_RULES.NUMERALS },
  { word: "trzeci", correctAnswer: "rz", rule: RZ_RULES.NUMERALS },
  { word: "trzeba", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "trzask", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "trzeszczenie", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "trzepot", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "trzoda", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "trzewik", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "trzęsienie", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "drzemka", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "drzwi", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "drzeć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rozrzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rozrzucić - rzut" },
  { word: "krzywy", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "skrzyżowanie", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "skrzypce", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "skrzynia", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "skrzydło", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "skrzętny", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wyrzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wyrzucić - rzut" },
  { word: "wyrzuty", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wyrzuty - rzut" },
  { word: "wyrzec", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wyrzec - rzut" },
  { word: "zarzut", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "zarzut - rzucić" },
  { word: "zarzucać", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "zarzucać - rzut" },
  { word: "zarzewie", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "otrzeć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "otrzeć - tarcie" },
  { word: "otrzeźwić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "otrzeźwić - rześki" },
  { word: "zatrzeć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "zatrzeć - tarcie" },
  { word: "zatrzasnąć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "zatrząść", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzask", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzenie", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzosy", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wrzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "wrzucić - rzut" },
  { word: "pomarzyć", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "pomarzyć - mara" },
  { word: "przerwać", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "przerwać - przerwa" },
  { word: "przyrząd", correctAnswer: "rz", rule: RZ_RULES.PREFIXES },
  { word: "narzędzia", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "narząd", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "porzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "porzucić - rzut" },
  { word: "rządami", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rządami - rząd" },
  { word: "rzędowy", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzędowy - rząd" },
  { word: "rzędem", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzędem - rząd" },
  { word: "rzęsisty", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "rzutki", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzutki - rzut" },
  { word: "rzutować", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzutować - rzut" },
  { word: "rzutnik", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "rzutnik - rzut" },
  { word: "dorzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "dorzucić - rzut" },
  { word: "narzucić", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "narzucić - rzut" },
  { word: "narzuta", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "narzuta - rzut" },
  { word: "dorzecze", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "dorzecze - rzeka" },
  { word: "orzeczenie", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "orzeczenie - rzeka" },
  { word: "orzec", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "orzec - rzeka" },
  { word: "orzekać", correctAnswer: "rz", rule: RZ_RULES.ALTERNATING_WITH_R, example: "orzekać - rzeka" },
  { word: "podbrzusze", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "obrzęd", correctAnswer: "rz", rule: RZ_RULES.MEMORIZE },
  { word: "obrzydliwy", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "pobrzeże", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "wybrzeże", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "nabrzeże", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "zabrzeże", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "podgrzewacz", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "rozgrzewać", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "grzałka", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "zgrzyt", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "zgrzeszyć", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
  { word: "zgrzebło", correctAnswer: "rz", rule: RZ_RULES.AFTER_CONSONANTS },
];

const zWordsList = [
  { word: "żebro", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeton", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeglować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żmudny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółtko", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "nóż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nóż - noże" },
  { word: "mąż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mąż - mężowie" },
  { word: "straż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "straż - strażnik" },
  { word: "stróż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "stróż - stróże" },
  { word: "drażnić", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drażnić - drażniący" },
  { word: "grożenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "grozić - grożenie" },
  { word: "mrożony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mrozić - mrożony" },
  { word: "poważać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "waga - poważać" },
  { word: "pożar", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pożyczka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "rażący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "razić - rażący" },
  { word: "sążeń", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "świeżo", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS },
  { word: "wiążący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wiązać - wiążący" },
  { word: "żaba", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żal", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żart", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żądać", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żelazo", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żniwa", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żona", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółw", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żurek", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyletka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyto", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywioł", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywność", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "bożonarodzeniowy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "bożonarodzeniowy - Bóg" },
  { word: "drużyna", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drużyna - druh" },
  { word: "dłużej", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dłużej - długi" },
  { word: "duży", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "duży - dużo" },
  { word: "książka", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "książka - księga" },
  { word: "krążek", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "krążek - krąg" },
  { word: "leżeć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "leżeć - lęgać" },
  { word: "łoże", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "łoże - lęgać" },
  { word: "możesz", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "możesz - mogę" },
  { word: "odważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "odważny - waga" },
  { word: "pieniężny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "pieniężny - pieniądz" },
  { word: "potężny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "potężny - potęga" },
  { word: "świeży", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS },
  { word: "jeży", correctAnswer: "ż", rule: Z_RULES.ADJECTIVE_ENDINGS },
  { word: "może", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "może - mogę", context: "On {word} przyjść jutro na spotkanie" },
  { word: "aż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "życie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żądanie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żądza", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żagiel", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żałoba", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żaluzja", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żarówka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żarliwy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeglarz", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żenujący", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeński", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żerować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żłobek", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żłób", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żmija", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żołądek", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żonaty", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żołnierz", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółty", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żubr", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żuć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żuk", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żuraw", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żwir", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "życzenie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "życzyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyła", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywić", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywot", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyzny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "bożyszcze", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "bożyszcze - Bóg" },
  { word: "drążyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drążyć - drążek" },
  { word: "dłuższy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dłuższy - długi" },
  { word: "dłużny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dłużny - dług" },
  { word: "dłużnik", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dłużnik - dług" },
  { word: "głożyna", correctAnswer: "ż", rule: Z_RULES.MEMORIZE, context: "{word} jest rodzajem krzewu lub niewielkiego drzewa z rodziny szakłakowatych" },
  { word: "grożący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "grożący - grozić" },
  { word: "jeż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "jeżeli", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "jeżyna", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "każdy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "krążyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "krążyć - krąg" },
  { word: "krzyż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "książę", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "książę - księga" },
  { word: "lżejszy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "lżejszy - lekki" },
  { word: "łyżka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "łyżwa", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "małżeństwo", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "małżeństwo - mąż" },
  { word: "mężczyzna", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mężczyzna - mąż" },
  { word: "młodzież", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "możliwy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "możliwy - mogę" },
  { word: "mróż", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mróż - mrozić" },
  { word: "nieżyczliwy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "nieżyt", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "niżej", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "niżej - niski" },
  { word: "niższy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "niższy - niski" },
  { word: "ogniożerca", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pięknoróża", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podłoże", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "podłoże - lęgać" },
  { word: "położyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "położyć - lęgać" },
  { word: "porażka", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "porażka - razić" },
  { word: "pożegnanie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "prażona", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "prażona - prażyć" },
  { word: "prażyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "prężyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różnica", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różowy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "ryż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "rzężączka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "rzeżąc", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "skarżyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "skarżyć - skarga" },
  { word: "skażony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "skażony - skazić" },
  { word: "służba", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "służba - służyć" },
  { word: "służący", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "służący - służyć" },
  { word: "służyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "snażny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "spożycie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "spożycie - spożyć" },
  { word: "spożywczy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "spożywczy - spożyć" },
  { word: "spożyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "stażysta", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "stażysta - staż" },
  { word: "strażak", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "strażak - straż" },
  { word: "strużka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "strzeżony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "strzeżony - strzec" },
  { word: "szeżyc", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "urżnąć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "usłużyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "usłużyć - służyć" },
  { word: "użyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wdrażać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wdrażać - drążyć" },
  { word: "wdrożenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wdrożenie - drążyć" },
  { word: "wdrożyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wdrożyć - drążyć" },
  { word: "wieża", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wrażenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wrażenie - wrazić" },
  { word: "wraży", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wróżba", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wróżyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wzdłuż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "zagrożenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zagrożenie - grozić" },
  { word: "załóżmy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "załóżmy - zakładać" },
  { word: "założyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "założyć - zakładać" },
  { word: "zamrożony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zamrożony - mrozić" },
  { word: "zarażenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zarażenie - zarazić" },
  { word: "zagrożony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zagrożony - grozić" },
  { word: "zbliżony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zbliżony - zbliżyć" },
  { word: "zbliżyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "zdążyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "złoże", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "złoże - lęgać" },
  { word: "złożony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "złożony - złożyć" },
  { word: "złożyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "złożyć - lęgać" },
  { word: "zmrużyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zmrużyć - mrużyć" },
  { word: "zniżka", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zniżka - niski" },
  { word: "znużony", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "znużony - nużyć" },
  { word: "zwycięży", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zwycięży - zwycięstwo" },
  { word: "żabka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żakiet", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żaglówka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żarcie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żargon", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żebrać", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żebrak", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żegnać", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żegnaj", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żel", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żelatyna", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żeliwo", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żetom", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żłobić", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żołd", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółtaczka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółcień", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żółknąć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żubrówka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żucie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żuławy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żupa", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żupan", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żur", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żwawość", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żwawy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żwirek", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "życzliwość", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "życiorys", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żylak", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyrandol", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żytni", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywica", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywiciel", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żyworodny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywopłot", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "żywiec", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "wrażliwy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wrażliwy - wrazić" },
  { word: "wrażliwość", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "wrażliwość - wrazić" },
  { word: "odważyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "odważyć - waga" },
  { word: "ciężar", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ciężar - ciąży" },
  { word: "ciężki", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ciężki - ciąży" },
  { word: "mężny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "mężny - mąż" },
  { word: "pieniążek", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "pieniążek - pieniądz" },
  { word: "drążek", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drążek - drążyć" },
  { word: "mżyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "mżawka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "niemożliwy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "niemożliwy - mogę" },
  { word: "rozmnożyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "rozmnożyć - mnożyć" },
  { word: "nóżka", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nóżka - nóż" },
  { word: "wieżowiec", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pasożyt", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pasożytniczy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "krzyżyk", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "krzyżować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "krzyżówka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podróż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podróżny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podróżować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podróżnik", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "próżny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "próżnia", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różnić", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "poróżnienie", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "zróżnicować", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różnorodny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różnobarwny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "róża", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różany", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różaniec", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "różdżka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "pudrowo-różowy", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "łóżko", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "łóżko - lęgać" },
  { word: "karaluż", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "podłużny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "podłużny - długi" },
  { word: "drużba", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "drużba - druh" },
  { word: "przysiężny", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "zakażenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "zakażenie - zakazić" },
  { word: "spostrzeżenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "spostrzeżenie - strzec" },
  { word: "dożywocie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dożywocie - żyć" },
  { word: "obciążenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "obciążenie - ciąży" },
  { word: "obciążyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "obciążyć - ciąży" },
  { word: "ściążka", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "ciążowy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ciążowy - ciąży" },
  { word: "ciąża", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ciąża - ciężar" },
  { word: "przeżyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "przeżyć - żyć" },
  { word: "przeżycie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "przeżycie - żyć" },
  { word: "przeżywać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "przeżywać - żyć" },
  { word: "dożyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dożyć - żyć" },
  { word: "dożywić", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dożywić - żywić" },
  { word: "dożywianie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "dożywianie - żywić" },
  { word: "pomnożyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "pomnożyć - mnożyć" },
  { word: "mnożyć", correctAnswer: "ż", rule: Z_RULES.MEMORIZE },
  { word: "rozmnażać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "rozmnażać - mnożyć" },
  { word: "ważyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ważyć - waga" },
  { word: "podważyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "podważyć - waga" },
  { word: "rozważyć", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "rozważyć - waga" },
  { word: "rozważać", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "rozważać - waga" },
  { word: "rozważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "rozważny - waga" },
  { word: "ważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ważny - waga" },
  { word: "ważniejszy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "ważniejszy - waga" },
  { word: "najważniejszy", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "najważniejszy - waga" },
  { word: "nieważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nieważny - waga" },
  { word: "poważny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "poważny - waga" },
  { word: "noża", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "noża - nóż" },
  { word: "nożny", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nożny - nóż" },
  { word: "nożyce", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nożyce - nóż" },
  { word: "nożyczki", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "nożyczki - nóż" },
  { word: "położenie", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "położenie - lęgać" },
  { word: "położna", correctAnswer: "ż", rule: Z_RULES.ALTERNATING, example: "położna - lęgać" },
];

export { rzWordsList, zWordsList };