// Pełna lista słów z "rz" i "ż" wraz z zasadami ortograficznymi
const allWordsList = [
  // Słowa z "rz"
  { word: "rzecz", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "rzeka", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych." },
  { word: "rzut", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych." },
  { word: "przyjaźń", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przestrzeń", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przyroda", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przyszłość", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "brzeg", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "brzoza", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "chrzan", correctAnswer: "rz", rule: "RZ piszemy w wyrazach, których pisownię należy zapamiętać." },
  { word: "drzewo", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "grzyb", correctAnswer: "rz", rule: "RZ piszemy w wyrazach, których pisownię należy zapamiętać." },
  { word: "krzyk", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "marzenie", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (marzyć - mara)." },
  { word: "orzech", correctAnswer: "rz", rule: "RZ piszemy w wyrazach, których pisownię należy zapamiętać." },
  { word: "porzeczka", correctAnswer: "rz", rule: "RZ piszemy w wyrazach, których pisownię należy zapamiętać." },
  { word: "rzadko", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (rzadko - rarytas)." },
  { word: "rzeźba", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (rzeźbić - rzeźbiarz)." },
  { word: "rzodkiewka", correctAnswer: "rz", rule: "RZ piszemy w wyrazach, których pisownię należy zapamiętać." },
  { word: "trzy", correctAnswer: "rz", rule: "RZ piszemy w liczebnikach zawierających 'trzy'." },
  { word: "wrzesień", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "wrzos", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "wrzawa", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "wrzeciono", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "wrzód", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "krzesło", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "krzyż", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "krzew", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "krzyczeć", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "krzywda", correctAnswer: "rz", rule: "RZ piszemy po spółgłoskach: p, b, t, d, k, g, ch, j, w." },
  { word: "przebaczenie", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przepis", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przegląd", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przejście", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przystanek", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przygoda", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przyjaciel", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "przykład", correctAnswer: "rz", rule: "RZ piszemy w przedrostkach prze-, przy-." },
  { word: "burza", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (burza - burzliwy)." },
  { word: "morze", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (morze - morski)." },
  { word: "górze", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (górze - góra)." },
  { word: "tworzyć", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (tworzyć - twór)." },
  { word: "powtórzyć", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (powtórzyć - powtór)." },
  { word: "przerwa", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (przerwa - przerwać)." },
  { word: "spojrzenie", correctAnswer: "rz", rule: "RZ piszemy, gdy wymienia się na 'r' w innych formach wyrazu lub wyrazach pokrewnych (spojrzenie - spozierać)." },
  { word: "żebro", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żeton", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żeglować", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żmudny", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żółtko", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "nóż", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (nóż - noże)." },
  { word: "mąż", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (mąż - mężowie)." },
  { word: "straż", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (straż - strażnik)." },
  { word: "stróż", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (stróż - stróże)." },
  { word: "drażnić", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (drażnić - drażniący)." },
  { word: "grożenie", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (grozić - grożenie)." },
  { word: "mrożony", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (mrozić - mrożony)." },
  { word: "poważać", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (waga - poważać)." },
  { word: "pożar", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "pożyczka", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "rażący", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (razić - rażący)." },
  { word: "sążeń", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "świeżo", correctAnswer: "ż", rule: "Ż piszemy w zakończeniach przymiotników -eży." },
  { word: "wiążący", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (wiązać - wiążący)." },
  { word: "żaba", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żal", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żart", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żądać", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żelazo", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żniwa", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żona", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żółw", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żurek", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żyć", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żyletka", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żyto", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żywioł", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "żywność", correctAnswer: "ż", rule: "Ż piszemy w wielu wyrazach, których pisownię należy zapamiętać." },
  { word: "bożonarodzeniowy", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (bożonarodzeniowy - Bóg)." },
  { word: "drużyna", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (drużyna - druh)." },
  { word: "dłużej", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (dłużej - długi)." },
  { word: "duży", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (duży - dużo)." },
  { word: "książka", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (książka - księga)." },
  { word: "krążek", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (krążek - krąg)." },
  { word: "leżeć", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (leżeć - lęgać)." },
  { word: "łoże", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (łoże - lęgać)." },
  { word: "możesz", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (możesz - mogę)." },
  { word: "odważny", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (odważny - waga)." },
  { word: "pieniężny", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (pieniężny - pieniądz)." },
  { word: "potężny", correctAnswer: "ż", rule: "Ż piszemy, gdy wymienia się na 'g', 'dz', 'h', 'z', 's' w innych formach wyrazu lub wyrazach pokrewnych (potężny - potęga)." },
  { word: "świeży", correctAnswer: "ż", rule: "Ż piszemy w zakończeniach przymiotników -eży." },
  { word: "jeży", correctAnswer: "ż", rule: "Ż piszemy w zakończeniach przymiotników -eży." }
];

export default allWordsList;